# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e410a74c44fdff1b7832ce4005409e799d20de68f81e463abee93268bf3d6d738442eb10b4eea29528c58926000588358ef0cda7aa8956cafe4c8545ecc5d59

test:
  secret_key_base: 4067b0f72e00ab4a87b4fc2a41223c3a2187c9261db313a9cc55a54a7980d92dcae8e4009d467a89e84765f66449e33237f64ce46f48c9c61fe16441c05a5576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
